#+TITLE: Geo tools for 3D printing

* Outline                                                             :TOC@2:
 - [[#presentation][Presentation]]
 - [[#license][License]]

* Presentation
This is a tool to work with geographic data for 3D printing.

* License
This work is licensed under the term of the [[https://www.gnu.org/licenses/gpl-3.0.html][GPL v3.0]] license:

#+BEGIN_QUOTE
Geo tools for 3D printing
Copyright (C) 2016 Fabien Dubosson <fabien.dubosson@gmail.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
#+END_QUOTE

See [[file:LICENSE.md][LICENSE.md]] for the complete license.
